AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SQS-Lambdas

  Sample SAM Template for SQS-Lambdas

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs12.x

Resources:
 
 FeedGeneratorQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      DelaySeconds: 0
      FifoQueue: true
      KmsDataKeyReusePeriodSeconds: 86400 # 24 hours, for details
      # KmsMasterKeyId: String    # default will be used (aws managed)
      MaximumMessageSize: 10240 # 10 KB
      MessageRetentionPeriod: 600 # 1 minute
      QueueName: FeedGeneratorQueue.fifo
      ReceiveMessageWaitTimeSeconds: 20 # 20 seconds(max), For long polling
      # RedrivePolicy:                    # to attach a dead-letter-queue, this is different DLQ than the one used for fail cases.
      #   deadLetterTargetArn: String
      #   maxReceiveCount: Integer
      # Tags:
      #   - Tag
      VisibilityTimeout: 30 # 30 seconds

  FeedGeneratorQueueLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FeedGeneratorQueueLambdaFunction
      CodeUri: feed-generator-queue-lambda/
      Handler: dist/app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 256
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 10
            Enabled: true
            Queue: # ARN of queue
              Fn::Join:
                - ""
                - - "arn:aws:sqs:"
                  - Ref: "AWS::Region"
                  - ":"
                  - Ref: "AWS::AccountId"
                  - ":FeedGeneratorQueue.fifo"

      Policies:
        - AWSLambdaSQSQueueExecutionRole    # access permissions of SQS

        - DynamoDBCrudPolicy:
            TableName: GeneralPopTable
        





Outputs:
  FeedGeneratorQueue:
    Description: "URL of new FIFO SQS Queue for posting posts to be consumed by feed generator"
    Value:
      Ref: FeedGeneratorQueue
  FeedGeneratorQueueARN:
    Description: "ARN of new FIFO SQS Queue for posting posts to be consumed by feed generator"
    Value:
      Fn::GetAtt:
        - FeedGeneratorQueue
        - Arn

